// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_66gY3_juIPgWDaWaqGSp4X0Yt5ScTr0',
    appId: '1:205829397512:web:24b9114be0ca2b1f0745bd',
    messagingSenderId: '205829397512',
    projectId: 'project-mercury-prototype',
    authDomain: 'project-mercury-prototype.firebaseapp.com',
    storageBucket: 'project-mercury-prototype.appspot.com',
    measurementId: 'G-WXLP3Q37BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsoU55HtjBf0r3SSc8F2OvSy3BcmPVyGc',
    appId: '1:205829397512:android:c4a0b32b064c3a700745bd',
    messagingSenderId: '205829397512',
    projectId: 'project-mercury-prototype',
    storageBucket: 'project-mercury-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmUV5hcTnjr_iPv0XA286r6PNeFJQJd60',
    appId: '1:205829397512:ios:e7bc252800bc6d870745bd',
    messagingSenderId: '205829397512',
    projectId: 'project-mercury-prototype',
    storageBucket: 'project-mercury-prototype.appspot.com',
    iosBundleId: 'com.example.projectmercury',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmUV5hcTnjr_iPv0XA286r6PNeFJQJd60',
    appId: '1:205829397512:ios:e7bc252800bc6d870745bd',
    messagingSenderId: '205829397512',
    projectId: 'project-mercury-prototype',
    storageBucket: 'project-mercury-prototype.appspot.com',
    iosBundleId: 'com.example.projectmercury',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp8RwsvTU9Jro4NGllXpXsMuFLPSeNqlg',
    appId: '1:205829397512:web:5dcb8f8e25b8cd220745bd',
    messagingSenderId: '205829397512',
    projectId: 'project-mercury-prototype',
    authDomain: 'project-mercury-prototype.firebaseapp.com',
    storageBucket: 'project-mercury-prototype.appspot.com',
    measurementId: 'G-C1RB06RN9P',
  );

}